### ISSUE TITLE
关于已经停止的作业

### ISSUE THREAD

**Issue by dongliuqingqing** [yurhett/OpenPAI-HENU#2]
怎么让状态已经停止的作业重新运行
![1699151827360](https://github.com/yurhett/OpenPAI-HENU/assets/74712229/64649378-6b56-43ec-b335-de7830e3a724)

**Comment by yurhett** [comment]
克隆旧的作业是唯一方法。

**Comment by dongliuqingqing** [comment]
已经完成或者不再进行的作业，我这边有权限删除吗

**Comment by dongliuqingqing** [comment]
> 克隆旧的作业是唯一方法。

已经完成或者不再进行的作业，我这边有权限删除吗

**Comment by yurhett** [comment]
> > 克隆旧的作业是唯一方法。
> 
> 已经完成或者不再进行的作业，我这边有权限删除吗

没有，官方并不提供删除的功能。enjoy

**Comment by dongliuqingqing** [comment]
> > > 克隆旧的作业是唯一方法。
> > 
> > 
> > 已经完成或者不再进行的作业，我这边有权限删除吗
> 
> 没有，官方并不提供删除的功能。enjoy
能通过SSH用pycharm进行远程开发吗

**Comment by yurhett** [comment]
> > > > 克隆旧的作业是唯一方法。
> > > 
> > > 
> > > 已经完成或者不再进行的作业，我这边有权限删除吗
> > 
> > 
> > 没有，官方并不提供删除的功能。enjoy
> > 能通过SSH用pycharm进行远程开发吗

可以，但注意这并非官方支持的，不建议使用。除nfs持久存储以外，你的所有数据将不会保存。这意味着使用有额外步骤，如有兴趣，请留言你的邮件地址，SSH配置可以发给你。

**Comment by dongliuqingqing** [comment]
> > > > > 克隆旧的作业是唯一方法。
> > > > 
> > > > 
> > > > 已经完成或者不再进行的作业，我这边有权限删除吗
> > > 
> > > 
> > > 没有，官方并不提供删除的功能。enjoy
> > > 能通过SSH用pycharm进行远程开发吗
> 
> 可以，但注意这并非官方支持的，不建议使用。除nfs持久存储以外，你的所有数据将不会保存。这意味着使用有额外步骤，如有兴趣，请留言你的邮件地址，SSH配置可以发给你。
那发我一下吧，我想试试，我的邮件地址2239967500@qq.com，感谢
