### ISSUE TITLE
nltk超时问题

### ISSUE THREAD

**Issue by ylxwan** [yurhett/OpenPAI-HENU#3]
我的代码中需要使用nltk库去下载punkt、stopwords、wordnet这三个资源，但是当我使用python -m nltk.downloader去下载的时候，总是会出现网络超时情况。 我在网上了解到这是正常的现象，解决办法是我们可以手动下载punkt、stopwords、wordnet这三个对应的压缩包，然后将其解压到下面任意一个路径即可：
```
Searched in:
    - '/root/nltk_data'
    - '/opt/conda/nltk_data'
    - '/opt/conda/share/nltk_data'
    - '/opt/conda/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
```
可是因为这个不是自己的电脑，我应该没有权限去做这件事，有什么解决办法吗？

**Comment by yurhett** [comment]
可以，运行时的容器是即用即弃的虚拟电脑，你只需要上传到存储，copy到你指定的目录即可。

**Comment by ylxwan** [comment]
好的，谢谢你
