### ISSUE TITLE
服务器的操作系统

### ISSUE THREAD

**Issue by ylxwan** [yurhett/OpenPAI-HENU#4]
我的代码在配置环境的时候，有一个库一直安装超时。于是我手动下载wheel文件后，上传到服务器。但是在使用pip进行本地安装的时候，总是报错说该wheel不被该平台支持。所有我想问问是什么操作系统？不知道是否和这个有关系

**Comment by yurhett** [comment]
操作系统是Ubuntu Linux，wheel需要你首先安装相应的编译器，并非平台不支持。

**Comment by ylxwan** [comment]
能具体点吗？安装编译器是什么意思？报错信息是这样的。
ERROR: dgl-1.1.1+cu113-cp39-cp39-manylinux1_x86_64.whl is not a supported wheel on this platform。
是指需要python版本不匹配吗？

**Comment by yurhett** [comment]
版本不匹配 并非平台故障 请自查 换用合适镜像
