### ISSUE TITLE
apt安装问题

### ISSUE THREAD

**Issue by wangyu1213888** [yurhett/OpenPAI-HENU#5]
import cv2 时报错ImportError: libGL.so.1: cannot open shared object file: No such file or direc，再使用apt-get安装，一直提示E: Unable to locate package libgl1-mesa-glx，此外，用apt-get安装其他的软件包也是提示E: Unable to locate package。我想问下这种情况怎么解决？

**Comment by yurhett** [comment]
你进行apt update了吗？只要是apt有的包 就能正常运行 请自查
